apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s101-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s101-app
  template:
    metadata:
      labels:
        app: k8s101-app
    spec:
      containers:
        - name: k8s101-node
          image: momil56/kubernetes101-demo-image:latest
